(function(root){
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const i=n=>`<i data-lucide="${n}" aria-hidden="true"></i>`;
const platforms={remote:['远程','cloud'],ios:['iOS','smartphone'],android:['安卓','tablet-smartphone'],termux:['Termux','terminal']};
const hints={remote:'填入服务提供的 HTTPS /mcp 地址。',ios:'接入兼容的 iOS 桥接。普通网页工具请选择远程。',android:'系统功能需要安卓桥接与对应权限。',termux:'本地 stdio 工具需要先启动 Termux 桥接。'};
const btn=(a,t,d='',primary=false,busy=false)=>`<button type="button" class="mc-btn ${primary?'mc-primary':''}" data-action="${a}" ${d} ${busy?'disabled':''}>${t}</button>`;
const heading=(title,sub='')=>`<div class="mc-page-heading"><h2>${title}</h2>${sub?`<span>${h(sub)}</span>`:''}</div>`;
const code=(id,text)=>`<div class="mc-code-block"><pre id="${id}">${h(text)}</pre><button data-action="copy-code" data-code="${id}">复制</button></div>`;
const toggle=(key,label,checked,desc,id)=>`<label class="mc-setting-row"><span><b>${label}</b><small>${desc}</small></span><input type="checkbox" data-role-setting="${key}" data-role-id="${h(id)}" ${checked?'checked':''}><span class="mc-switch" aria-hidden="true"></span></label>`;
function shell(){return `<header class="mc-head"><button class="mc-icon" data-action="home" aria-label="返回桌面">${i('house')}</button><div class="mc-brand">mcp</div><button class="mc-header-text" data-tab="tutorial">教程</button><button class="mc-icon" data-tab="help" aria-label="设置">${i('menu')}</button></header><main class="mc-body"></main><nav class="mc-nav">${[['services','link-2','连接'],['roles','user-round','角色'],['logs','menu','日志'],['chat','message-circle','试聊']].map(([id,icon,t])=>`<button data-tab="${id}" aria-current="false">${i(icon)}<span>${t}</span></button>`).join('')}</nav>`;}
function page(s){const {tab,services=[],states={},busy=false,transcript=[],logs=[],aiConfig={},selected='',characters=[],preferences={},notice=''}=s;const tools=services.flatMap(x=>(states[x.id]?.tools||[]).map(t=>({s:x,t})));
if(tab==='services')return `${heading('连接',services.length+' 个服务')}${notice?`<div class="mc-success mc-sr-only" role="status">${h(notice)}</div>`:''}<div class="mc-service-list">${services.map(x=>{const state=states[x.id],p=platforms[x.platform]?x.platform:'remote';return `<article class="mc-service"><div class="mc-service-main"><span class="mc-avatar">${i(platforms[p][1])}</span><div class="mc-service-copy"><b>${h(x.name)}</b><small>${platforms[p][0]}${state?.ready?' · '+state.tools.length+' 个工具':''}</small></div><button class="mc-icon" data-action="edit" data-id="${h(x.id)}" aria-label="编辑 ${h(x.name)}">${i('ellipsis')}</button></div><div class="mc-service-bottom"><span class="mc-status ${state?.ready?'is-connected':''}"><span></span>${state?.connecting?'连接中':state?.ready?'已连接':state?.paused?'已断开':state?.error?'连接失败':'未连接'}</span><div class="mc-service-actions">${state?.ready||state?.connecting?`<button class="mc-disconnect" data-action="disconnect" data-id="${h(x.id)}">断开连接</button>`:''}<button class="mc-connect" data-action="connect" data-id="${h(x.id)}" ${state?.connecting?'disabled':''}>${state?.connecting?'连接中…':state?.ready?'重新连接':'连接'}</button></div></div>${state?.error&&!state?.paused?`<p class="mc-service-error">${h(state.error)} · 将自动重试</p>`:''}</article>`;}).join('')||`<div class="mc-empty">${i('plug')}<b>添加你的第一个连接</b><p>从远程 MCP 地址开始。</p></div>`}</div><button class="mc-add" data-action="new">${i('square-plus')} 添加连接</button><div class="mc-quick-links"><button data-tab="tools">工具目录</button></div>`;
if(tab==='tools')return `${heading('工具目录',tools.length+' 个可用')}<div class="mc-search">${i('search')}<input id="mc-search" placeholder="搜索名称或功能" aria-label="搜索工具"></div><div class="mc-tools-grid">${tools.map(({s,t},index)=>`<article class="mc-tool-card" data-tool-card data-search="${h((t.name+' '+(t.description||'')).toLowerCase())}"><span class="mc-eyebrow">${h(s.name)}</span><h3>${h(t.title||t.name)}</h3><p>${h(t.description||'暂无描述')}</p>${btn('tool','测试工具',`data-index="${index}"`)}</article>`).join('')||'<div class="mc-empty"><b>暂无工具</b><p>先在连接页面连接服务。</p></div>'}</div>`;
if(tab==='roles')return `${heading('角色','404 私聊')}<p class="mc-description">点击角色，设置调用权限与卡片显示。</p>${characters.map(c=>{const p=KissMCPRuntime.policy(c);return `<details class="mc-role-card"><summary><span class="mc-role-avatar">${c.avatar?`<img src="${h(c.avatar)}" alt="">`:i('user-round')}</span><span><b>${h(c.remarkName||c.realName||'角色')}</b><small>${!p.enabled?'已关闭 MCP':p.auto?'可主动选择工具':'仅按用户要求调用'} · ${p.showCard?'聊天显示卡片':'仅记录日志'}</small></span></summary><div class="mc-role-body">${toggle('enabled','允许使用 MCP',p.enabled,'作用于这个角色的 404 私聊。',c.id)}${toggle('auto','允许主动调用',p.auto,'每轮判断是否需要工具；不需要则不调用。',c.id)}${toggle('showCard','在聊天显示调用卡片',p.showCard,'关闭后仅在活动日志查看。',c.id)}<div class="mc-service-access"><b>可用连接</b>${services.map(x=>`<label><input type="checkbox" data-role-service="${h(x.id)}" data-role-id="${h(c.id)}" ${p.serviceIds===null||p.serviceIds.includes(x.id)?'checked':''}>${h(x.name)}</label>`).join('')||'<small>还没有添加连接。</small>'}</div></div></details>`;}).join('')||'<div class="mc-empty"><b>还没有角色</b><p>先在 404 添加角色。</p></div>'}`;
if(tab==='logs')return `${heading('活动日志',logs.length+' 条记录')}<div class="mc-log-controls"><label>自动清理<select id="mc-retention">${[[3,'三天前的日志'],0,1,7,30].map(x=>{const [n,t]=Array.isArray(x)?x:[x,x===0?'不自动清理':x+' 天前的日志'];return `<option value="${n}" ${Number(preferences.retentionDays)===n?'selected':''}>${t}</option>`;}).join('')}</select></label><div><button data-action="select-logs">选择</button><button data-action="clear-logs">清空日志</button></div></div><div class="mc-log-filters"><input id="mc-log-search" placeholder="搜索角色 / 工具" aria-label="搜索日志"><select id="mc-log-status"><option value="all">全部状态</option><option value="success">成功</option><option value="failure">失败</option><option value="running">正在调用</option></select></div><div class="mc-selected-actions" hidden><button data-action="delete-selected">删除选中日志</button><button data-action="select-all-logs">全选</button></div><div class="mc-timeline">${logs.map(l=>`<article class="mc-log-row" data-log-row data-search="${h((l.actor+' '+l.tool+' '+l.service).toLowerCase())}" data-status="${l.status}"><input type="checkbox" class="mc-log-select" value="${h(l.id)}" hidden ${l.status==='running'?'disabled':''}><button class="mc-log-open" data-action="log-detail" data-id="${h(l.id)}"><time>${new Date(l.startedAt).toLocaleTimeString('zh-CN',{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'})}<small>${new Date(l.startedAt).toLocaleDateString('zh-CN')}</small></time><span><b>${h(l.actor)}</b><small>${h(l.tool)} · ${h(l.service)}</small></span><em class="mc-log-state ${l.status}">${l.status==='success'?'成功':l.status==='failure'?'失败':'调用中'}</em></button></article>`).join('')||'<div class="mc-empty"><b>还没有活动</b><p>角色和试聊的真实调用都会记录在这里。</p></div>'}</div><p class="mc-footnote">默认保留最近三天。打开页面与页面运行期间自动清理，关闭网页时不运行。清理日志不删除聊天卡片。</p>`;
if(tab==='chat')return `${heading('试聊')}<details class="mc-details mc-ai-settings"><summary>AI 接口设置</summary>${btn('inherit','读取小手机 API 设置')}<label>API 地址</label><input id="mc-ai-url" value="${h(aiConfig.url)}" placeholder="https://…/v1"><label>模型</label><input id="mc-ai-model" value="${h(aiConfig.model)}"><label>API Key</label><input id="mc-ai-key" type="password" value="${h(aiConfig.key)}" autocomplete="off"></details><label>本轮连接</label><select id="mc-chat-service">${services.map(x=>`<option value="${h(x.id)}" ${selected===x.id?'selected':''}>${h(x.name)}</option>`).join('')||'<option value="">还没有连接</option>'}</select><div class="mc-conversation">${transcript.map(m=>m.role.startsWith('工具')?`<details class="mc-tool-message"><summary>${i(m.status==='failure'?'asterisk':'check')} ${h(m.role)} · ${m.status==='failure'?'失败':'成功'}</summary><pre class="mc-code">${h(m.text)}</pre></details>`:`<div class="mc-bubble ${m.role==='你'?'mc-user':''}">${h(m.text)}</div>`).join('')||'<div class="mc-chat-empty">发送链接，试一次读取。</div>'}</div><div class="mc-composer"><textarea id="mc-chat-text" rows="1" placeholder="发一个链接，或说点什么…" aria-label="试聊消息"></textarea><button class="mc-send" data-action="send" aria-label="发送" ${busy?'disabled':''}>发送</button></div><div class="mc-chat-controls"><button data-action="stop" ${!busy?'disabled':''}>停止生成</button><button data-action="clear-chat" ${busy?'disabled':''}>清空试聊</button></div>`;
if(tab==='tutorial')return `${heading('接入教程')}<p class="mc-description">选一种方式：已有远程地址用 HTTP；本地 stdio 工具用 Termux。</p><div class="mc-faq"><details open><summary>HTTP / HTTPS · 远程 MCP</summary><div class="mc-guide-note"><p><b>1. 拿到服务的 MCP 地址</b><br>服务必须支持 Streamable HTTP。一般是 https://服务域名/mcp，具体路径以服务说明为准。普通网页、小红书分享链接不能放在这里。</p><p><b>2. 在小手机添加连接</b><br>MCP → 连接 → 添加连接 → 远程。填名称、完整 MCP 地址；服务有 Token 时填原始 Token，不用加 Bearer。保存后自动连接，出现「已连接」和工具数量就可用。</p><p><b>3. 给角色使用</b><br>在「角色」中允许 MCP，勾选连接。到 404 发链接，再按平常方式生成回复，即可读取；想让角色主动决定调用则打开主动调用。</p><p><b>你的已有小红书服务</b></p><code>https://xhs-xsj-can.petrusoclarnon.workers.dev/mcp</code><p>iPhone 和安卓都能用远程 HTTP 接入，不需要安装 Termux。公开网页使用 HTTPS；HTTP localhost 只用于本机开发，手机浏览器不一定允许 HTTPS 页面直连本地 HTTP。</p></div></details><details><summary>Termux · 安卓本地 MCP 桥接</summary><div class="mc-guide-note"><p>这个教程从本包附带的文本统计示例开始，先确认能连通，再换你需要的 stdio MCP。Termux 只适用于安卓。</p><p><b>1. 安装 Termux，准备运行环境</b><br>从 <a href="https://github.com/termux/termux-app#installation" target="_blank" rel="noopener noreferrer">Termux 官方安装说明</a>选择安装包。打开后逐段粘贴命令；存储访问弹窗选择允许。</p>${code('ter-install',`pkg update
pkg install nodejs cloudflared unzip
termux-setup-storage`)}<p><b>2. 下载并解压这个更新包</b><br>先点 <a href="termux/Termux_MCP_bridge.zip" download="Termux_MCP_bridge.zip">下载 Termux 桥接文件</a>，把 Termux_MCP_bridge.zip 放在手机 Download 文件夹。下面的命令解压到 mcp-bridge；若你改过下载文件名，先改回来。</p>${code('ter-unzip',`cd ~/storage/downloads
unzip Termux_MCP_bridge.zip -d mcp-bridge
cd mcp-bridge/termux
sh start.sh`)}<p>看到 MCP bridge listening 即已启动。start.sh 第一次会生成访问 Token 并保存在 .bridge-token，之后启动沿用同一个 Token。这个会话保持运行；按 Ctrl+C 可停止。</p><p><b>3. 新开一个 Termux 会话，创建 HTTPS 地址</b><br>从 Termux 侧边栏选择 NEW SESSION，再执行：</p>${code('ter-tunnel',`cloudflared tunnel --url http://127.0.0.1:8787`)}<p>终端会给你一个 https://…trycloudflare.com 地址，把它复制下来并在末尾加 /mcp。隧道会话也要保持运行。此入门桥接使用 JSON HTTP 响应；临时隧道不支持 SSE，其他要求 SSE 的服务应换合适的固定隧道。</p><p><b>4. 再开一个会话，查看自己的 Token</b></p>${code('ter-token',`cd ~/storage/downloads/mcp-bridge/termux
cat .bridge-token`)}<p>小手机 → MCP → 添加连接 → Termux。地址填第 3 步的 HTTPS 地址加 /mcp；Token 填第 4 步输出。保存自动连接后，在工具目录测试 text_stats，参数示例：</p>${code('ter-test',`{"text":"你好，小mi"}`)}<p><b>5. 换成需要的本地工具</b><br>修改 termux/server.json 的 command、args、env，让它启动你选定的 MCP stdio 服务，然后 Ctrl+C 停止桥接并再次 sh start.sh。服务需要哪些 API 密钥、依赖或手机权限，以该服务文档为准；示例不会自动获得通知等系统功能。</p><p>每次重新创建临时隧道，地址会改变，需要编辑小手机连接地址。长期使用请配置固定域名隧道。临时隧道停止或安卓杀掉 Termux 进程后，小手机无法自行把它启动。</p><p><a href="https://developers.cloudflare.com/tunnel/get-started/quick-tunnels/" target="_blank" rel="noopener noreferrer">Cloudflare 临时隧道官方说明</a></p></div></details><details><summary>自动连接和断开连接</summary><p>配置保存后、刷新页面、重新打开小手机、网络恢复时，会自动连接。页面打开期间每分钟检查一次工具列表；失败会按间隔重试，不会重复执行之前的工具。</p><p>点「断开连接」会停止正在连接的请求和该服务当前的调用，并暂停此服务的自动重连；刷新后也保持断开。再次点「连接」才恢复自动连接。</p><p>为了刷新后能自动鉴权，Token 保存在当前浏览器的本机存储中，不会随连接配置导出。旧版只存在页面内存的 Token 需要重新填写并保存一次。</p><p>这只能维护网页连接，不能在网页关闭时继续运行，也不能代替 Termux 后台进程保活。</p></details><details><summary>连不上时检查什么？</summary><p>确认是完整 MCP 地址而不是网站首页；检查 Token、网络、服务是否允许当前小手机网页的 Origin，以及 Content-Type、Authorization、Mcp-Session-Id、MCP-Protocol-Version 请求头。Termux 则同时确认桥接和隧道两个会话都在运行。</p></details></div>`;
return `${heading('设置')}<div class="mc-settings-list"><button data-action="export">导出连接配置</button><button data-action="import">导入连接配置</button></div><p class="mc-footnote">连接和 Token 保存在本机，用于刷新后自动连接。导出配置不包含 Token。</p>`;
}
function form(x={},token='',platform='remote'){platform=x.platform||platform;return `${heading(x.id?'编辑连接':'添加连接')}<form id="mc-form"><label>运行环境</label><div class="mc-platforms">${Object.entries(platforms).map(([p,[name,icon]])=>`<label><input type="radio" name="platform" value="${p}" ${platform===p?'checked':''}><span>${i(icon)}${name}</span></label>`).join('')}</div><p class="mc-platform-hint" id="mc-platform-hint">${h(hints[platform])}</p><label>名称</label><input name="name" required maxlength="60" value="${h(x.name)}" placeholder="给连接起个名字"><label>MCP 地址</label><input name="url" type="url" required value="${h(x.url)}" placeholder="https://…/mcp"><label>Bearer Token（可选）</label><input name="token" type="password" value="${h(token)}" autocomplete="off" placeholder="仅填写 Token"><div class="mc-actions"><button class="mc-btn mc-primary" type="submit">保存连接</button>${btn('cancel','返回')}${x.id?btn('remove','删除连接',`data-id="${h(x.id)}"`):''}</div></form>`;}
function tool(item,args){return `${heading('工具测试',h(item.s.name))}<h3 class="mc-detail-title">${h(item.t.name)}</h3><p class="mc-description">${h(item.t.description)}</p><details class="mc-details"><summary>参数格式</summary><pre class="mc-code">${h(JSON.stringify(item.t.inputSchema,null,2))}</pre></details><label>调用参数 · JSON</label><textarea id="mc-args" rows="6">${h(JSON.stringify(args,null,2))}</textarea><div class="mc-actions">${btn('run','运行工具','',true)}${btn('cancel','返回工具')}</div><div id="mc-result"></div>`;}
root.KissMCPView={shell,page,form,tool,platformText:p=>hints[p]||'',h};
})(globalThis);
